on:
  push:
    branches:
         - main

name: if_else_test

jobs:
  if_condition:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - run: echo "You are in Main Branch :)"  && echo github.workflow
         name: IF
         if: github.ref == 'refs/heads/main'
       - run: echo "You are not in dev branch :("
         name: Else
         if: contains(github.ref, 'dev')
