on:
  push:
    branches:
         - master

name: if_else_test

jobs:
  if_condition:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - run: echo "You are in Main Branch :)"
         name: IF
         if: contains(github.ref, "main")
       - if: ${GITHUB_REF##*/} != "main"
         name: Else
         run: echo "You are not in main Branch :("
